/**
 * dsh-volcengine — DeepSeek Harness bundle plugin for Volcano Engine (火山引擎).
 *
 * The plugin registers model-facing tools that call Volcengine Ark's
 * OpenAI-compatible bearer endpoints. The bundle's `cordis.patch.yml`
 * additionally configures the bundled `@deepseek-ai/dsh-llm-pi-ai` adapter
 * with a `volcengine` provider route so Ark models join the model picker.
 *
 * Built from TypeScript with tsdown: `lib/index.js` is generated by the
 * `prepare` script, and `@deepseek-ai/dsh-tools` stays external so the single
 * runtime import resolves from the host installation (no duplicate copies).
 */

import type { Context } from '@deepseek-ai/cordis'
import type {} from '@deepseek-ai/dsh-tools'
import { volcengineChatTool } from './lib/chat.ts'
import { volcengineImageTool } from './lib/image.ts'
import { DEFAULT_BASE_URL } from './lib/ark.ts'
import type { VolcengineOptions } from './lib/ark.ts'

export const name = 'volcengine'
export const inject = ['tools']

const DEFAULT_CHAT_MODEL = 'deepseek-v3-250324'
const DEFAULT_IMAGE_MODEL = 'doubao-seedream-4-0-250828'

/** Plugin config, set on the `volcengine` row in `cordis.patch.yml`. */
export interface Config {
  /** Env var holding the Ark API key (default `ARK_API_KEY`). */
  apiKeyEnv?: string
  /** Literal key; prefer `apiKeyEnv`. */
  apiKey?: string
  /** Ark base URL (default `https://ark.cn-beijing.volces.com/api/v3`). */
  baseURL?: string
  /** Default chat model id / endpoint id for `volcengine_chat`. */
  chatModel?: string
  /** Default image model id for `volcengine_image_generate`. */
  imageModel?: string
}

export function apply(ctx: Context, config: Config = {}): void {
  const resolve = (): VolcengineOptions => {
    const apiKeyEnv = config.apiKeyEnv ?? 'ARK_API_KEY'
    const apiKey = config.apiKey ?? process.env[apiKeyEnv]
    if (!apiKey) {
      throw new Error(
        `dsh-volcengine: no Volcengine Ark API key. Export ${apiKeyEnv} in the launching environment,`
        + ' or set `apiKeyEnv` / `apiKey` on the `volcengine` row config.',
      )
    }
    return {
      baseURL: config.baseURL ?? process.env.ARK_BASE_URL ?? DEFAULT_BASE_URL,
      apiKey,
      chatModel: config.chatModel ?? DEFAULT_CHAT_MODEL,
      imageModel: config.imageModel ?? DEFAULT_IMAGE_MODEL,
    }
  }

  ctx.tools.register(volcengineChatTool(resolve))
  ctx.tools.register(volcengineImageTool(resolve))
}
